import type { Metadata } from 'next';
import './globals.css';

import ThemeProvider from '@/components/themeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ThemeProvider>
        <body className={`w-screen h-screen p-4`}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
