import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='w-screen h-screen flex flex-col overflow-hidden'>
        <header className='flex items-center justify-between p-4 bg-teal-200 text-black font-extrabold'>
          <Link href='/'>Home</Link>
          <Link href='/auth/register'>Register</Link>
        </header>
        <div className='p-4 mb-4 flex-1 overflow-y-scroll'>{children}</div>
        <footer className='flex items-center justify-center p-4 bg-teal-200 text-black font-extrabold mt-auto'>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
